version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver
    ports:
      - '1234:1234'

  celery-worker:
    build: .
    container_name: celery-worker
    entrypoint: celery
    command: -A parser.celery worker --loglevel=info
    environment:
        CELERY_BROKER_URL: "redis://redis:6379/0"
        CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
    - .:/var/www/app/worker
    links:
    - redis
    depends_on:
    - redis

  redis:
    image: redis
    restart: always
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
    container_name: redis

#
#volumes:
#  postgres_data:
#  redis:
#  logging:
#  static:
