# Generated by Django 5.0 on 2024-01-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parser_habr", "0002_remove_hub_task_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Timer",
        ),
    ]
