# Generated by Django 5.0 on 2024-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_habr", "0004_alter_author_author_alter_author_author_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hub",
            name="hub_link",
            field=models.URLField(
                max_length=255, unique=True, verbose_name="Ссылка на хаб"
            ),
        ),
    ]
