# Generated by Django 5.0 on 2024-01-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parser_mel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
