# Generated by Django 5.0 on 2024-01-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parser_mel", "0002_remove_article_author_delete_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="task_id",
        ),
    ]
