# Generated by Django 5.0 on 2024-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_tink", "0002_remove_category_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="link_cat",
            field=models.URLField(
                max_length=10000, unique=True, verbose_name="Ссылка на категорию"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_cat",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Категория"
            ),
        ),
    ]
